# Generated by Django 5.0.6 on 2024-06-11 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('profile', models.CharField(choices=[('Myself', 'Myself'), ('Friend', 'Friend'), ('Sister', 'Sister'), ('Brother', 'Brother'), ('Parent', 'Parent')], default='Myself', max_length=150)),
                ('email', models.EmailField(default='example@gmail.com', max_length=100, unique=True)),
                ('password', models.CharField(default='12345', max_length=128)),
                ('cast', models.CharField(default='General', max_length=15)),
                ('image', models.ImageField(default='profile/default.webp', upload_to='profile/')),
                ('height', models.FloatField(default='5.5')),
                ('weight', models.FloatField(default='30')),
                ('address', models.CharField(default='None', max_length=255)),
                ('contact', models.CharField(default='0000000000', max_length=15)),
                ('dob', models.DateField(default='2000-01-01')),
                ('marital_status', models.CharField(choices=[('Never Married', 'Never Married'), ('Widowed', 'Widowed'), ('Divorced', 'Divorced'), ('Awaiting divorce', 'Awaiting divorce')], default='Never Mrried', max_length=20)),
                ('family_status', models.CharField(choices=[('Middle class', 'Middle class'), ('Upper middle class', 'Upper middle class'), ('High class', 'High class'), ('Rich/Affluent', 'Rich/Affluent')], default='Middle class', max_length=20)),
                ('family_type', models.CharField(choices=[('Joint', 'Joint'), ('Nuclear', 'Nuclear')], default='Nuclear', max_length=20)),
                ('family_values', models.CharField(choices=[('Orthodox', 'Orthodox'), ('Traditional', 'Traditional'), ('Moderate', 'Moderate'), ('Liberal', 'Liberal')], default='Liberal', max_length=20)),
                ('disability', models.CharField(choices=[('None', 'None'), ('Physically challenged', 'Physically challenged')], default='None', max_length=25)),
            ],
        ),
    ]
