# Generated by Django 5.0.6 on 2024-06-13 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cast',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='profile',
            name='contact',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='profile',
            name='disability',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Physically challenged', 'Physically challenged')], max_length=25),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dob',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='family_status',
            field=models.CharField(blank=True, choices=[('Middle class', 'Middle class'), ('Upper middle class', 'Upper middle class'), ('High class', 'High class'), ('Rich/Affluent', 'Rich/Affluent')], max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='family_type',
            field=models.CharField(blank=True, choices=[('Joint', 'Joint'), ('Nuclear', 'Nuclear')], max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='family_values',
            field=models.CharField(blank=True, choices=[('Orthodox', 'Orthodox'), ('Traditional', 'Traditional'), ('Moderate', 'Moderate'), ('Liberal', 'Liberal')], max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='height',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('Never Married', 'Never Married'), ('Widowed', 'Widowed'), ('Divorced', 'Divorced'), ('Awaiting divorce', 'Awaiting divorce')], max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='password',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile',
            field=models.CharField(blank=True, choices=[('Myself', 'Myself'), ('Friend', 'Friend'), ('Sister', 'Sister'), ('Brother', 'Brother'), ('Parent', 'Parent')], max_length=150),
        ),
        migrations.AlterField(
            model_name='profile',
            name='weight',
            field=models.FloatField(blank=True),
        ),
    ]
