# Generated by Django 5.0.6 on 2024-06-15 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_profile_gender_alter_profile_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mother_tounge',
            field=models.CharField(blank=True, choices=[('Malayalam', 'Malayalam'), ('Tamil', 'Tamil'), ('Hindi', 'Hindi'), ('English', 'English'), ('Kannada', 'Kannada'), ('Telugu', 'Telugu')], max_length=50),
        ),
    ]
