# Generated by Django 5.0.6 on 2024-06-15 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0004_alter_profile_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cast',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='disability',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Physically challenged', 'Physically challenged')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='family_status',
            field=models.CharField(blank=True, choices=[('Middle class', 'Middle class'), ('Upper middle class', 'Upper middle class'), ('High class', 'High class'), ('Rich/Affluent', 'Rich/Affluent')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='family_type',
            field=models.CharField(blank=True, choices=[('Joint', 'Joint'), ('Nuclear', 'Nuclear')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='family_values',
            field=models.CharField(blank=True, choices=[('Orthodox', 'Orthodox'), ('Traditional', 'Traditional'), ('Moderate', 'Moderate'), ('Liberal', 'Liberal')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('Never Married', 'Never Married'), ('Widowed', 'Widowed'), ('Divorced', 'Divorced'), ('Awaiting divorce', 'Awaiting divorce')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mother_tounge',
            field=models.CharField(blank=True, choices=[('Malayalam', 'Malayalam'), ('Tamil', 'Tamil'), ('Hindi', 'Hindi'), ('English', 'English'), ('Kannada', 'Kannada'), ('Telugu', 'Telugu')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
