# Generated by Django 5.0.6 on 2024-06-27 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0008_profile_about'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='mother_tounge',
            new_name='mother_tongue',
        ),
    ]
